version: '2.2'
services:
  cerebro:
    image: lmenezes/cerebro:0.8.3
    container_name: cerebro
    ports:
      - "9000:9000"
    command:
      - -Dhosts.0.host=http://elasticsearch:9200
    networks:
      - es8net
  kibana:
    image: docker.elastic.co/kibana/kibana:8.18.0
    container_name: kibana8
    environment:
      - I18N_LOCALE=zh-CN
      - XPACK_GRAPH_ENABLED=true
      - TIMELION_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED="true"
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=c69548d9027afcf4d55146b1d425a9f4c69548d9027afcf4d55146b1d425a9f4
    ports:
      - "5601:5601"
    networks:
      - es8net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.0
    container_name: es8_01
    environment:
      - cluster.name=geektime
      - node.name=es8_01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.seed_hosts=es8_01,es8_02
      - cluster.initial_master_nodes=es8_01,es8_02
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es8data1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - es8net
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.0
    container_name: es8_02
    environment:
      - cluster.name=geektime
      - node.name=es8_02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.seed_hosts=es8_01,es8_02
      - cluster.initial_master_nodes=es8_01,es8_02
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es8data2:/usr/share/elasticsearch/data
    networks:
      - es8net


volumes:
  es8data1:
    driver: local
  es8data2:
    driver: local

networks:
  es8net:
    driver: bridge